export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubiks cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A giant pink elephant riding a unicycle on a beach',
  'A group of cats wearing top hats and monocles playing poker',
  'A robot made entirely out of cupcakes',
  'A dragon flying through a city made of candy',
  'A unicorn jumping over a rainbow made of spaghetti',
  'A mermaid sitting on a rock playing a guitar made of shells',
  'A giant robot fighting a giant monster in a futuristic city',
  'A dragon-shaped hot air balloon flying over a castle',
  'A giant robot shaped like a dinosaur',
  'A group of cartoon characters playing baseball on a cloud',
  'A robot cleaning a giant robot in space',
  'A dragon playing a banjo in a field of flowers',
  'A robot chef cooking a meal for a group of robots',
  'A group of aliens playing a game of soccer on a UFO',
  'A robot dog playing fetch with a robot cat',
  'A giant robot fighting a giant robot in a city',
  'A robot DJ spinning records at a robot dance party',
  'A landscape in the style of Vincent van Gogh',
  'A portrait in the style of Frida Kahlo',
  'A still life in the style of Salvador Dali',
  'A cityscape in the style of Claude Monet',
  'A seascape in the style of J.M.W Turner',
  'A landscape in the style of Paul Cezanne',
  'A portrait in the style of John Singer Sargent',
  'A still life in the style of Paul Klee',
  'A cityscape in the style of Pablo Picasso',
  'A seascape in the style of Edvard Munch',
  'A landscape in the style of Gustav Klimt',
  'A portrait in the style of Gustav Klimt',
  'A still life in the style of Georges Seurat',
  'A cityscape in the style of Marc Chagall',
  'A seascape in the style of Hokusai',
  'A landscape in the style of Pierre-Auguste Renoir',
  'A portrait in the style of John Everett Millais',
  'A still life in the style of Jan Vermeer',
  'A cityscape in the style of Henri Matisse',
  'A seascape in the style of Winslow Homer',
  'A mountain range with snow-capped peaks and a river flowing through it',
  'A sunset over a tropical beach with palm trees',
  'A waterfall surrounded by lush green forest',
  'A serene lake surrounded by autumn colored trees',
  'A valley with colorful wildflowers and a rainbow in the sky',
  'A desert landscape with towering sand dunes and a setting sun',
  'A hot air balloon floating above a picturesque countryside',
  'A rainbow arching over a majestic waterfall',
  'A majestic castle on a hilltop overlooking a picturesque town',
  'A panoramic view of a city skyline at night',
  'A cherry blossoms in full bloom along a tranquil river bank',
  'A snowy mountain peak with an eagle soaring above',
  'A forest with a canopy of orange, yellow and red leaves',
  'A secluded beach with crystal clear water and white sand',
  'A Northern Lights show over a frozen lake',
  'A floating island with a palace made of crystal and a waterfall',
  'A giant tree with a house built into it and a rope bridge connecting it to other trees',
  'A volcano with a lake of lava and a rainbow-colored smoke',
  'A canyon with a river of chocolate and marshmallow mountains',
  'A forest with giant mushrooms and a talking animals',
  'A beach with a giant shell-shaped castle and a mermaids',
  'A sky full of stars and a planet that is inhabited by unicorns',
  'A underwater city made of glass and a school of colorful fish',
  'A island with a giant robot that is shaped like a dragon and a volcano',
  'A meadow with a giant flowers and a giant bumblebee',
  'A valley with a giant rainbow and a talking rabbits',
  'A desert with a giant cactus that has a city on top of it',
  'A jungle with a giant snake that has a city on top of it',
  'A mountain with a giant castle on top of it and a dragon flying around it',
  'A tundra with a giant igloo and a polar bear driving a snowmobile',
];

